openapi: 3.0.3
info:
  title: Demo APIs
  description: Demo APIs
  version: 1.0.0
servers:
  - url: 'http://test.com/demo/v1'

paths:
  /resource:
    summary: retrive resource list
    get:
      parameters:
        - name: limit
          description: define the size of response list size
          in: query
        - name: page
          description: define the starting page number
          in: query
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  description: resource object
                  type: object
                  properties:
                    id:
                      type: string
            text/xml:
              schema:
                type: array
                items:
                  description: resource object
                  type: object
                  properties:
                    id:
                      type: string




  
